// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'text_field_examples.dart';

// **************************************************************************
// Generator: CodeSnaphostGeneretor
// **************************************************************************

extension TextFieldExamplesSourceCode on TextFieldExamples {
  get sourceCode {
    return "import 'package:annotations/annotations.dart';\n"
        "import 'package:example/example.dart';\n"
        "import 'package:flutter/material.dart';\n"
        "import 'package:flutter/src/widgets/framework.dart';\n"
        "import 'package:fotonica_ui_components/fotonica_text_field.dart';\n"
        "\n"
        "part 'text_field_examples.g.dart';\n"
        "\n"
        "@generateCodeSnapshot\n"
        "class TextFieldExamples extends Example {\n"
        "  @override\n"
        "  get code => sourceCode;\n"
        "\n"
        "  @override\n"
        "  State<StatefulWidget> createState() {\n"
        "    return TextFieldExamplesState();\n"
        "  }\n"
        "}\n"
        "\n"
        "class TextFieldExamplesState extends State<TextFieldExamples> {\n"
        "  bool showPassword = false;\n"
        "  String password = \"\";\n"
        "\n"
        "  @override\n"
        "  Widget build(BuildContext context) {\n"
        "    return ListView(\n"
        "      shrinkWrap: true,\n"
        "      children: [\n"
        "        Text(\"\"),\n"
        "        FotonicaTextField(\n"
        "            label: \"Label\",\n"
        "            placeholder: \"Placeholder\",\n"
        "            controller: TextEditingController(text: \"\"),\n"
        "            onChange: (v) {}),\n"
        "        FotonicaTextField(\n"
        "            label: \"E-mail\",\n"
        "            prefixIcon: Icon(Icons.email),\n"
        "            placeholder: \"Placeholder\",\n"
        "            controller: TextEditingController(text: \"\"),\n"
        "            onChange: (v) {}),\n"
        "        FotonicaTextField(\n"
        "          label: \"Password\",\n"
        "          prefixIcon: Icon(Icons.password),\n"
        "          suffixIcon: Wrap(\n"
        "            children: [\n"
        "              IconButton(\n"
        "                  onPressed: () {\n"
        "                    setState(() {\n"
        "                      showPassword = !showPassword;\n"
        "                    });\n"
        "                  },\n"
        "                  icon: Icon(showPassword ? Icons.remove_red_eye : Icons.close))\n"
        "            ],\n"
        "          ),\n"
        "          placeholder: \"Password\",\n"
        "          obscureText: showPassword,\n"
        "        ),\n"
        "        FotonicaTextField(\n"
        "          label: \"Label\",\n"
        "          placeholder: \"Placeholder\",\n"
        "          suffixIcon: Wrap(\n"
        "            children: [\n"
        "              IconButton(\n"
        "                onPressed: () {},\n"
        "                icon: Icon(Icons.code),\n"
        "              ),\n"
        "              IconButton(\n"
        "                onPressed: () {},\n"
        "                icon: Icon(Icons.extension),\n"
        "              )\n"
        "            ],\n"
        "          ),\n"
        "        )\n"
        "      ],\n"
        "    );\n"
        "  }\n"
        "}\n"
        "\n";
  }
}
